basic mocha specs added for #patch

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,3 +1,12 @@
 GULP="node_modules/.bin/gulp"
 
-$GULP $@
+while :; do
+  echo "stating gulp..."
+  $GULP $@
+  echo "error status: $?"
+  echo "restarting in 1 sec"
+  echo
+  sleep 1
+done
+
+
